language: node_js

dist: trusty

node_js:
  - "6"

before_install:
  - "npm config set spin false"
  - "npm --version"
  - "npm install coveralls"
  - "rm -f /tmp/*.dmp"
  - "google-chrome --version"

install:
  - "npm install"

after_success:
  - "cat test/coverage/*/lcov.info | node_modules/coveralls/bin/coveralls.js"

notifications:
  email:
    recipients:
      - travis@plusnew.io
    on_success: change
    on_failure: always
