language: node_js

node_js:
  - "5"

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm --version"
  - npm install grunt-cli -g
  - npm install jshint -g
  - "phantomjs --version"
  - "rm -f /tmp/*.dmp"

install:
  - "npm install"
  - "grunt default"

notifications:
  email:
    recipients:
      - travis@snew.io
    on_success: change
    on_failure: always
