language: node_js

dist: trusty

node_js:
  - "6"

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta

before_install:
  - "export CHROME_BIN=google-chrome-beta"
  - "npm config set spin false"
  - "npm --version"
  - "npm install gulp -g"
  - "npm install tslint -g"
  - "rm -f /tmp/*.dmp"
  - "google-chrome --version"

install:
  - "npm install"
  - "gulp default"

after_success:
  - "gulp coveralls"

notifications:
  email:
    recipients:
      - travis@snew.io
    on_success: change
    on_failure: always
